#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_349_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_32_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_309_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_33_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_307_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_34_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_346_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_35_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_298_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_36_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_299_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_37_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_300_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_38_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_325_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_39_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_011_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_40_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_012_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_41_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_047_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_42_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_328_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_43_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_051_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_44_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_048_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_45_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_050_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_46_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_049_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_47_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_324_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_48_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_010_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_49_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_009_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_50_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_338_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_51_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_174_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_52_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_326_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_53_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_046_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_54_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_038_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_55_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_036_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_56_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_034_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_57_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_032_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_58_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_031_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_59_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_030_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_60_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_029_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_61_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_027_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_62_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_025_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_63_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_019_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_64_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_017_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_65_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_016_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_66_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_015_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_67_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_014_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_68_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_118_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_69_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_121_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_70_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_330_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_71_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_064_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_72_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_063_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_73_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_060_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_74_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_058_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_75_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_333_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_76_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_090_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_77_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_332_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_78_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_085_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_79_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_084_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_80_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_087_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_81_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_334_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_82_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_344_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_83_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_291_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_84_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_286_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_85_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_283_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_86_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_274_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_87_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_343_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_88_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_232_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_89_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_233_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_90_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_235_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_91_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_238_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_92_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_239_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_93_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_243_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_94_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_244_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_95_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_245_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_96_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_247_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_97_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_248_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_98_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_249_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_99_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_250_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_100_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_251_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_101_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_253_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_102_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_255_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_103_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_256_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_104_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_258_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_105_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_260_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_106_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_261_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_107_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_262_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_108_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_263_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_109_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_264_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_110_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_266_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_111_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_267_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_112_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_268_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_113_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_269_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_114_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_271_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_115_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_331_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_116_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_083_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_117_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_081_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_118_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_080_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_119_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_079_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_120_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_078_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_121_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_077_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_122_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_076_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_123_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_075_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_124_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_074_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_125_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_073_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_126_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_072_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_127_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_071_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_128_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_070_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_129_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_069_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_130_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_337_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_131_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_171_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_132_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_172_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_133_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_184_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_134_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_183_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_135_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_179_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_136_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_177_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_137_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_176_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_138_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_175_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_139_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_163_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_140_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_164_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_141_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_165_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_142_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_166_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_143_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_167_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_144_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_168_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_145_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_169_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_146_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_170_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_147_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_342_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_148_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_189_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_149_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_191_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_150_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_193_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_151_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_194_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_152_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_197_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_153_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_198_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_154_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_199_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_155_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_202_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_156_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_203_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_157_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_204_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_158_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_205_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_159_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_206_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_160_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_207_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_161_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_208_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_162_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_209_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_163_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_210_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_164_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_211_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_165_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_212_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_166_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_213_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_167_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_214_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_168_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_215_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_169_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_216_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_170_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_217_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_171_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_218_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_172_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_219_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_173_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_220_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_174_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_221_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_175_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_222_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_176_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_224_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_177_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_225_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_178_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_226_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_179_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_227_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_180_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_228_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_181_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_229_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_182_DTF_table.txt
#wget https://bio.liclab.net/scBlood_static/detail_table/TF_table/scBlood_h_230_DTF_table.txt -O /mnt/m/keti/database/sc_variant/table/chromVAR/source/sample_id_183_DTF_table.txt
